pid_list={
    "104":"Engine load",
    "105":"Engine coolant temperature",
    "10A":"Fuel pressure",
    "10B":"Intake manifold absolute pressure",
    "10C":"Engine RPM",
    "10D":"Vehicle speed",
    "10E":"Timing advance",
    "10F":"Intake air temperature",
    "110":"MAF air flow rate",
    "111":"Throttle position",
    "11F":"Run time since engine start",
    "121":"Distance traveled with malfunction indicator lamp",
    "12F":"Fuel Level Input",
    "131":"Distance traveled since codes cleared",
    "133":"Barometric pressure",
    "142":"Control module voltage",
    "143":"Absolute load value",
    "15B":"Hybrid battery pack remaining life",
    "15C":"Engine oil temperature",
    "15E":"Engine fuel rate",
    "11":"UTC Date (DDMMYY)",
    "10":"UTC Time (HHMMSSmm)",
    "A":"Latitude",
    "B":"Longitude",
    "C":"Altitude (m)",
    "D":"Speed (km/h)",
    "E":"Course (degree)",
    "F":"Number of sAtellites in use",
    "20":"Accelerometer data (x:y:z)",
    "21":"Gyroscope data (x:y:z)",
    "22":"Magnitude field data (x/y/z)",
    "23":"MEMS temperature (in 0.1 Celsius degree)",
    "24":"Battery voltage (in 0.01V)",
    "25":"Orientation data  (yaw/pitch/roll)",
    "81":"Cellular network signal level (dB)",
    "82":"CPU temperature (in 0.1 Celsius degree)",
    "83":"CPU hall sensor data",
}